"use client";

import { useEffect, useRef, useState } from "react";
import { invoke } from "@tauri-apps/api/core";
import { listen } from "@tauri-apps/api/event";
import type { Terminal } from "@xterm/xterm";
import type { SearchAddon } from "@xterm/addon-search";
import {
  getTermFontSize,
  terminalFontFamily,
  TERM_FONT_EVENT,
} from "@/lib/view-prefs";

interface TerminalViewProps {
  cwd: string;
  /** Backend PTY session id — generated by the parent so it owns the tab. */
  sessionId: string;
  /** Fired once the shell has been spawned and is accepting input. */
  onReady?: () => void;
  /** Fired when the shell exits on its own (e.g. the user typed `exit`). */
  onExit?: () => void;
  /**
   * Fired when the shell reports a directory change via OSC 7 (emitted by the
   * projm shell-integration scripts on every prompt). Parents can use it to
   * label tabs or spawn siblings in the same directory.
   */
  onCwdChange?: (cwd: string) => void;
}

export default function TerminalView({
  cwd,
  sessionId,
  onReady,
  onExit,
  onCwdChange,
}: TerminalViewProps) {
  const containerRef = useRef<HTMLDivElement>(null);
  const termRef = useRef<Terminal | null>(null);
  const searchAddonRef = useRef<SearchAddon | null>(null);
  const [searchOpen, setSearchOpen] = useState(false);
  const searchInputRef = useRef<HTMLInputElement>(null);
  // Keep callbacks in refs so their identity never re-runs the init effect.
  const onReadyRef = useRef(onReady);
  const onExitRef = useRef(onExit);
  const onCwdChangeRef = useRef(onCwdChange);
  useEffect(() => {
    onReadyRef.current = onReady;
    onExitRef.current = onExit;
    onCwdChangeRef.current = onCwdChange;
  });

  useEffect(() => {
    // `listen` and the dynamic imports are async; if this effect is torn down
    // (StrictMode mount→cleanup→remount in dev) before they resolve, dispose
    // whatever arrives late instead of leaking it.
    let disposed = false;
    let unlistenData: (() => void) | null = null;
    let unlistenExit: (() => void) | null = null;
    let resizeObserver: ResizeObserver | null = null;
    let onFontChange: ((e: Event) => void) | null = null;
    let raf = 0;

    async function initTerminal() {
      // Dynamically import xterm to prevent SSR build failures
      const [
        { Terminal },
        { FitAddon },
        { SearchAddon },
        { WebLinksAddon },
        { ClipboardAddon },
        { Unicode11Addon },
      ] = await Promise.all([
        import("@xterm/xterm"),
        import("@xterm/addon-fit"),
        import("@xterm/addon-search"),
        import("@xterm/addon-web-links"),
        import("@xterm/addon-clipboard"),
        import("@xterm/addon-unicode11"),
      ]);
      await import("@xterm/xterm/css/xterm.css");

      if (disposed || !containerRef.current) return;

      const term = new Terminal({
        cursorBlink: true,
        fontFamily: terminalFontFamily(),
        fontSize: getTermFontSize(),
        lineHeight: 1.2,
        scrollback: 10_000,
        allowProposedApi: true,
        theme: {
          background: "#0c0d0e", // Carbon background
          foreground: "#e2e8f0",
          cursor: "#cbd5e1",
          black: "#1e293b",
          red: "#ef4444",
          green: "#22c55e",
          yellow: "#eab308",
          blue: "#3b82f6",
          magenta: "#a855f7",
          cyan: "#06b6d4",
          white: "#f8fafc",
        },
      });

      const fitAddon = new FitAddon();
      const searchAddon = new SearchAddon();
      term.loadAddon(fitAddon);
      term.loadAddon(searchAddon);
      term.loadAddon(
        new WebLinksAddon((_event: MouseEvent, uri: string) => {
          // Open in the system browser — window.open is a no-op in the webview.
          import("@tauri-apps/plugin-shell")
            .then((m) => m.open(uri))
            .catch((err) => console.error("failed to open link", err));
        })
      );
      term.loadAddon(new ClipboardAddon());
      term.loadAddon(new Unicode11Addon());
      term.unicode.activeVersion = "11";

      // OSC 7: the shell-integration scripts report cwd as a file:// URI on
      // every prompt — track it without parsing prompt text.
      term.parser.registerOscHandler(7, (data: string) => {
        const m = data.match(/^file:\/\/[^/]*(\/.*)$/);
        if (m) {
          try {
            onCwdChangeRef.current?.(decodeURIComponent(m[1]));
          } catch {
            onCwdChangeRef.current?.(m[1]);
          }
        }
        return true;
      });

      term.open(containerRef.current);

      // Renderer preference: GPU (WebGL) → Canvas → DOM. The packaged webview
      // frequently can't get a WebGL context that dev does (WebKitGTK without
      // the compositing env, WebView2 with GPU disabled), which silently drops
      // xterm to the DOM renderer — the source of the release-only typing lag.
      // Canvas is an order of magnitude faster than DOM, so fall back to it
      // instead of straight to DOM.
      const loadCanvasFallback = async () => {
        try {
          const { CanvasAddon } = await import("@xterm/addon-canvas");
          if (!disposed) term.loadAddon(new CanvasAddon());
        } catch (e) {
          console.warn("Canvas renderer unavailable, using DOM renderer", e);
        }
      };
      try {
        const { WebglAddon } = await import("@xterm/addon-webgl");
        const webgl = new WebglAddon();
        // On context loss, drop WebGL and pick up Canvas rather than DOM.
        webgl.onContextLoss(() => {
          webgl.dispose();
          void loadCanvasFallback();
        });
        term.loadAddon(webgl);
      } catch (err) {
        console.warn("WebGL renderer unavailable, falling back to Canvas", err);
        await loadCanvasFallback();
      }

      fitAddon.fit();

      // Re-fit once the mono webfont has finished loading so the grid is sized
      // against the real glyph metrics instead of a fallback font.
      document.fonts?.ready
        .then(() => {
          if (!disposed && termRef.current) fitAddon.fit();
        })
        .catch(() => {});

      // Live-apply terminal font-size changes from Settings without a reload.
      onFontChange = (e: Event) => {
        const px = (e as CustomEvent<number>).detail;
        if (typeof px === "number" && termRef.current) {
          termRef.current.options.fontSize = px;
          fitAddon.fit();
        }
      };
      window.addEventListener(TERM_FONT_EVENT, onFontChange);

      termRef.current = term;
      searchAddonRef.current = searchAddon;

      // Clipboard + search keys. Plain Ctrl+C must stay SIGINT for the shell.
      term.attachCustomKeyEventHandler((ev: KeyboardEvent) => {
        if (ev.type !== "keydown" || !ev.ctrlKey || !ev.shiftKey) return true;
        const key = ev.key.toLowerCase();
        if (key === "c") {
          const sel = term.getSelection();
          if (sel) navigator.clipboard?.writeText(sel).catch(() => {});
          return false;
        }
        if (key === "v") {
          navigator.clipboard
            ?.readText()
            .then((text) => text && term.paste(text))
            .catch(() => {});
          return false;
        }
        if (key === "f") {
          setSearchOpen(true);
          setTimeout(() => searchInputRef.current?.focus(), 0);
          return false;
        }
        return true;
      });

      // Listen to keystrokes and pipe to this session's PTY.
      term.onData((data) => {
        invoke("cmd_write_terminal", { id: sessionId, input: data }).catch(
          (err) => console.error("Failed to write to terminal stdin", err)
        );
      });

      // Keep the PTY the same size as the rendered grid. fit() only emits
      // onResize when the dimensions actually changed, so this self-dedupes.
      term.onResize(({ cols, rows }) => {
        invoke("cmd_resize_terminal", { id: sessionId, cols, rows }).catch(
          () => {}
        );
      });

      // Events are namespaced per session, so no payload filtering is needed.
      // Attach BEFORE spawning so the first prompt is never missed.
      const subData = await listen<{ data: string }>(
        `terminal-data:${sessionId}`,
        (event) => {
          term.write(event.payload.data);
        }
      );
      if (disposed) {
        subData();
        return;
      }
      unlistenData = subData;

      const subExit = await listen(`terminal-exit:${sessionId}`, () => {
        onExitRef.current?.();
      });
      if (disposed) {
        subExit();
        return;
      }
      unlistenExit = subExit;

      // Spawn the shell at the already-fitted size so it never starts 80×24.
      try {
        await invoke("cmd_spawn_terminal", {
          id: sessionId,
          cwd,
          cols: term.cols,
          rows: term.rows,
        });
        if (!disposed) onReadyRef.current?.();
      } catch (err) {
        term.write(
          `\r\n\x1b[31mFailed to spawn shell process in ${cwd}: ${err}\x1b[0m\r\n`
        );
      }

      // Refit on any container size change (window, sidebar, panel splits) —
      // rAF-debounced so resize drags don't flood the PTY.
      resizeObserver = new ResizeObserver(() => {
        if (raf) return;
        raf = requestAnimationFrame(() => {
          raf = 0;
          const el = containerRef.current;
          // Hidden keepMounted tabs report 0×0 — skip until visible again.
          if (!el || el.clientWidth === 0 || el.clientHeight === 0) return;
          fitAddon.fit();
        });
      });
      resizeObserver.observe(containerRef.current);

      // Fit again after short delay to let layout settle
      setTimeout(() => {
        if (!disposed) fitAddon.fit();
      }, 200);
    }

    initTerminal();

    return () => {
      disposed = true;
      if (raf) cancelAnimationFrame(raf);
      if (resizeObserver) resizeObserver.disconnect();
      if (onFontChange) window.removeEventListener(TERM_FONT_EVENT, onFontChange);
      if (unlistenData) unlistenData();
      if (unlistenExit) unlistenExit();
      if (termRef.current) {
        termRef.current.dispose();
        termRef.current = null;
      }
      searchAddonRef.current = null;
    };
  }, [cwd, sessionId]);

  const runSearch = (backwards: boolean) => {
    const query = searchInputRef.current?.value ?? "";
    if (!query || !searchAddonRef.current) return;
    if (backwards) searchAddonRef.current.findPrevious(query);
    else searchAddonRef.current.findNext(query);
  };

  const closeSearch = () => {
    setSearchOpen(false);
    searchAddonRef.current?.clearDecorations?.();
    termRef.current?.focus();
  };

  return (
    <div className="relative h-full w-full overflow-hidden rounded-lg border border-border bg-background p-3">
      {searchOpen && (
        <div className="absolute right-3 top-3 z-10 flex items-center gap-1 rounded-md border border-border bg-card p-1 shadow-xl">
          <input
            ref={searchInputRef}
            placeholder="Search…"
            className="w-40 bg-transparent px-1.5 py-0.5 font-mono text-xs text-foreground outline-none placeholder:text-muted-foreground"
            onKeyDown={(e) => {
              if (e.key === "Enter") runSearch(e.shiftKey);
              if (e.key === "Escape") closeSearch();
            }}
          />
          <button
            onClick={closeSearch}
            className="rounded px-1 text-xs text-muted-foreground hover:bg-accent hover:text-foreground"
            title="Close (Esc)"
          >
            ×
          </button>
        </div>
      )}
      <div ref={containerRef} className="h-full w-full" />
    </div>
  );
}
